In [ ]:
import pandas as pd

# Load JSON lines from a file
df = pd.read_json("fashion_products_data.ldjson", lines=True)

# Display the DataFrame
print(df)

                                uniq_id            crawl_timestamp  \
0      26d41bdc1495de290bc8e6062d927729  2020-02-07 05:11:36 +0000
1      410c62298852e68f34c35560f2311e5a  2020-02-07 08:45:56 +0000
2      52e31bb31680b0ec73de0d781a23cc0a  2020-02-06 11:09:38 +0000
3      25798d6dc43239c118452d1bee0fb088  2020-02-07 08:32:45 +0000
4      ad8a5a196d515ef09dfdaf082bdc37c4  2020-02-06 14:27:48 +0000
...                                 ...                        ...
29995  976b6bda7076509778da69eb3fe0f59c  2020-02-06 23:53:43 +0000
29996  3006a520f71804b055d92216f5dc946d  2020-02-06 20:32:09 +0000
29997  45ea7c463997f4cd91851617edbfee32  2020-02-06 19:55:44 +0000
29998  2ecada524df6ff8c2d0c53a249cfcddc  2020-02-06 05:08:00 +0000
29999  a4e77b9b1addb68bdfc4b178ac27e7c2  2020-02-06 23:32:41 +0000

             asin                                        product_url  \
0      B07STS2W9T  https://www.amazon.in/Facon-Kalamkari-Handbloc...
1      B07N6TD2WL  https://www.amazon.in/Sf-Jeans-Pantaloons-T-Sh...
2      B07WJ6WPN1  https://www.amazon.in/LOVISTA-Traditional-Prin...
3      B07PYSF4WZ  https://www.amazon.in/People-Printed-Regular-T...
4      B082KXNM7X  https://www.amazon.in/Monte-Carlo-Cotton-Colla...
...           ...                                                ...
29995  B07FVRMFTX  https://www.amazon.in/Indian-Virasat-Pushp-Cha...
29996  B07RR3XYZD  https://www.amazon.in/Urban-Ranger-Pantaloons-...
29997  B07SSLSR9X  https://www.amazon.in/Peter-England-Striped-Re...
29998  B07P561W67  https://www.amazon.in/PINKY-PARI-Womens-Embroi...
29999  B07GPQ7V5W  https://www.amazon.in/Gutsy-Triple-Striped-Sle...

                                            product_name  \
0      LA' Facon Cotton Kalamkari Handblock Saree Blo...
1      Sf Jeans By Pantaloons Men's Plain Slim fit T-...
2      LOVISTA Cotton Gota Patti Tassel Traditional P...
3               People Men's Printed Regular fit T-Shirt
4      Monte Carlo Grey Solid Cotton Blend Polo Colla...
...                                                  ...
29995        Indian Virasat Women's Rayon Anarkali Kurta
29996  Urban Ranger by Pantaloons Men's Slim fit T-Shirt
29997            Peter England Men's Regular fit T-Shirt
29998  PINKY PARI Women's Embroidered Short Denim Str...
29999  Gutsy Men's Full Sleeve All Over Printed Navy ...

                                       image_urls__small  \
0      https://images-na.ssl-images-amazon.com/images...
1      https://images-na.ssl-images-amazon.com/images...
2      https://images-na.ssl-images-amazon.com/images...
3      https://images-na.ssl-images-amazon.com/images...
4      https://images-na.ssl-images-amazon.com/images...
...                                                  ...
29995  https://images-na.ssl-images-amazon.com/images...
29996  https://images-na.ssl-images-amazon.com/images...
29997  https://images-na.ssl-images-amazon.com/images...
29998  https://images-na.ssl-images-amazon.com/images...
29999  https://images-na.ssl-images-amazon.com/images...

                                                  medium  \
0      https://images-na.ssl-images-amazon.com/images...
1      https://images-na.ssl-images-amazon.com/images...
2      https://images-na.ssl-images-amazon.com/images...
3      https://images-na.ssl-images-amazon.com/images...
4      https://images-na.ssl-images-amazon.com/images...
...                                                  ...
29995  https://images-na.ssl-images-amazon.com/images...
29996  https://images-na.ssl-images-amazon.com/images...
29997  https://images-na.ssl-images-amazon.com/images...
29998  https://images-na.ssl-images-amazon.com/images...
29999  https://images-na.ssl-images-amazon.com/images...

                                                   large    browsenode  \
0      https://images-na.ssl-images-amazon.com/images...  1.968255e+09
1      https://images-na.ssl-images-amazon.com/images...  1.968123e+09
2      https://images-na.ssl-images-amazon.com/images...  1.968255e+09
3      https://images-na.ssl-images-amazon.com/images...  1.968123e+09
4      https://images-na.ssl-images-amazon.com/images...  1.968070e+09
...                                                  ...           ...
29995  https://images-na.ssl-images-amazon.com/images...  1.968255e+09
29996  https://images-na.ssl-images-amazon.com/images...  1.968123e+09
29997  https://images-na.ssl-images-amazon.com/images...  1.968123e+09
29998  https://images-na.ssl-images-amazon.com/images...  1.968255e+09
29999  https://images-na.ssl-images-amazon.com/images...  1.968123e+09

                            brand  ...  \
0                       LA' Facon  ...
1                             NaN  ...
2                         LOVISTA  ...
3                             NaN  ...
4                             NaN  ...
...                           ...  ...
29995                         NaN  ...
29996  Urban Ranger by Pantaloons  ...
29997                         NaN  ...
29998                  PINKY PARI  ...
29999                       Gutsy  ...

                                             colour no__of_reviews  \
0                                               NaN            NaN
1                                               NaN            NaN
2                                               NaN            NaN
3                                               NaN            NaN
4                                               NaN            NaN
...                                             ...            ...
29995                                           NaN            NaN
29996                                           NaN            NaN
29997                                           NaN            NaN
29998  DARK BLUE (BEIGE)|DARK BLUE (RED)|LIGHT BLUE            NaN
29999                                           NaN            NaN

       seller_name seller_id left_in_stock no__of_offers no__of_sellers  \
0              NaN       NaN           NaN           NaN            NaN
1              NaN       NaN           NaN           NaN            NaN
2              NaN       NaN           NaN           NaN            NaN
3              NaN       NaN           NaN           NaN            NaN
4              NaN       NaN           NaN           NaN            NaN
...            ...       ...           ...           ...            ...
29995          NaN       NaN           NaN           NaN            NaN
29996          NaN       NaN           NaN           NaN            NaN
29997          NaN       NaN           NaN           NaN            NaN
29998          NaN       NaN           NaN           NaN            NaN
29999          NaN       NaN           NaN           NaN            NaN

      technical_details__k_v_pairs formats___editions name_of_author_for_books
0                              NaN                NaN                      NaN
1                              NaN                NaN                      NaN
2                              NaN                NaN                      NaN
3                              NaN                NaN                      NaN
4                              NaN                NaN                      NaN
...                            ...                ...                      ...
29995                          NaN                NaN                      NaN
29996                          NaN                NaN                      NaN
29997                          NaN                NaN                      NaN
29998                          NaN                NaN                      NaN
29999                          NaN                NaN                      NaN

[30000 rows x 33 columns]

In [ ]:
import nltk
import string
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download necessary NLTK resources
  # Change this to your desired path
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')  # Download WordNet for lemmatization

# Initialize the stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Function to clean product names
def clean_product_name(name):
    # Convert to lowercase
    name = name.lower()

    # Remove punctuation
    name = name.translate(str.maketrans('', '', string.punctuation))

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(name)
    words = [word for word in words if word not in stop_words]  # Remove stopwords

    # Apply stemming and lemmatization
    words = [stemmer.stem(lemmatizer.lemmatize(word)) for word in words]  # Stem and lemmatize each word

    # Remove special keywords (example: 'new', 'sale', etc.)
    special_keywords = ['new', 'sale', 'has', '@', "$"]  # Add more as needed
    words = [word for word in words if word not in special_keywords]

    # Remove non-English words (this is a simple regex check)
    name = re.sub(r'[^a-zA-Z\s]', '', ' '.join(words))  # Join words back into a string

    # Convert short forms to long forms (example: 'w/' to 'with')
    short_forms = {'w/': 'with', 'b/': 'by'}  # Ensure this dictionary is defined
    for short, long in short_forms.items():
        name = name.replace(short, long)  # This line should work correctly

    return name

# Apply the cleaning function to the product_name column
df['product_name'] = df['product_name'].apply(clean_product_name)

# Keep only the specified columns
df = df[['asin', 'product_url', 'product_name', 'sales_price', 'rating', 'meta_keywords', 'medium', 'brand']]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df['product_name']

0        la facon cotton kalamkari handblock sare blous...
1              sf jean pantaloon men plain slim fit tshirt
2        lovista cotton gota patti tassel tradit print ...
3                       peopl men print regular fit tshirt
4        mont carlo grey solid cotton blend polo collar...
                               ...
29995            indian virasat woman rayon anarkali kurta
29996           urban ranger pantaloon men slim fit tshirt
29997                 peter england men regular fit tshirt
29998    pinki pari woman embroid short denim straight ...
29999               gutsi men full sleev print navi tshirt
Name: product_name, Length: 30000, dtype: object